Konloch/bytecode-viewer

src/main/java/the/bytecode/club/bytecodeviewer/JarUtils.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/JDGUIDecompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S2095 - “Resources should be closed”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2095
Please let me know if you have any questions.
Ayman Abdelghany.

[squid:S2095] Resources should be closed

---

src/main/java/jd/cli/util/ClassFileUtil.java
src/main/java/jd/cli/util/CommonTypeNameUtil.java
src/main/java/jd/cli/util/VersionUtil.java
src/main/java/org/apache/commons/cli/OptionValidator.java
src/main/java/org/apache/commons/cli/PatternOptionBuilder.java
src/main/java/org/apache/commons/cli/TypeHandler.java
src/main/java/org/apache/commons/cli/Util.java
src/main/java/org/apache/commons/codec/binary/CharSequenceUtils.java
src/main/java/org/apache/commons/codec/binary/StringUtils.java
src/main/java/org/apache/commons/codec/digest/DigestUtils.java
src/main/java/org/apache/commons/codec/digest/HmacUtils.java
src/main/java/org/apache/commons/codec/language/SoundexUtils.java
src/main/java/org/apache/commons/codec/net/Utils.java
src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/JarUtils.java
src/main/java/the/bytecode/club/bytecodeviewer/MiscUtils.java
src/main/java/the/bytecode/club/bytecodeviewer/api/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/FieldNodeDecompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/plugin/PluginManager.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S1118 - “Utility classes should not have public constructors ”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Ayman Abdelghany.

[squid:S1118] Utility classes should not have public constructors

---

src/the/bytecode/club/bootloader/Boot.java

java.lang.NullPointerException
at the.bytecode.club.bootloader.Boot.populateLibsDirectory(Boot.java:327)
at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:408)
This prevented at least Krakatau from working, because further
initialization in BytecodeViewer$3.run was inhibited.

Fixed NPE with fat Jar and clean working folder

---

src/the/bytecode/club/bytecodeviewer/Dex2Jar.java

Existing code did not work with .apk files, which contained "apk" substring in the filename.

Fixed dex2jar with filenames containing dex or apk

---

src/the/bytecode/club/bytecodeviewer/gui/FileNavigationPane.java

Without this class `a.b.c` will not be added if package `a.b` exists

Include .class in the name when comparing with the file tree

---

src/the/bytecode/club/bootloader/Boot.java

Without this it can fail to download krakatau or enjarify on machines without an already existing `.Bytecode-Viewer`

Properly create .Bytecode-Viewer/libs if it doesn't exist

---

src/the/bytecode/club/bytecodeviewer/compilers/JavaCompiler.java

Use path.separator to determine correct char

Fix class recompilation on linux

---

src/the/bytecode/club/bytecodeviewer/searching/RegexInsnFinder.java
src/the/bytecode/club/bytecodeviewer/searching/RegexSearch.java

Rewrite regex search so that it pattern checks each instruction without building a string of the whole method first. Regex duration on mobile cpu (i5-7200U) goes down from 2635ms to 430ms for one specific test case.

Speed-up regex search

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/MethodsRenderer.java

On Windows (and maybe other OSes, I haven't thoroughly checked), an `ArrayIndexOutOfBoundsException` would be called upon having most decompilers active when method lists were attempted to be found for them. That would result in the method dropdown not existing which would mess up Swing/AWT and result in many more exceptions related to screen rendering and some NPEs.
This PR catches that initial `ArrayIndexOutOfBoundsException` which ends up setting some other fields. That ends up fixing NPEs which fixes other exceptions as well.

fix bugs occurring on Windows when trying to generate the method list

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/VisibleComponent.java
src/main/java/the/bytecode/club/bytecodeviewer/plugin/PluginWriter.java

This resolves an outstanding issue allowing us to remove the
temporary fix for it. Also, the "frame.svg" icon is now loaded
using the official API and no longer relies on the exact location
of the resource.

Update darklaf to version 3.0.0

---

pom.xml

https://blogs.apache.org/maven/entry/apache-maven-shade-plugin-version6
> Release Notes - Maven Shade Plugin - Version 3.3.0
> 
> 
> ** Bug
>     * [MSHADE-252] - shadeSourcesContent is broken when combined with partial relocation
>     * [MSHADE-378] - Shade plugin changes the compression level of nested jar entries
>     * [MSHADE-396] - Improve SourceContent Shading
> 
> 
> ** New Feature
>     * [MSHADE-36] - Add option to include dependency reduced POM instead of original one
> 
> 
> ** Improvement
>     * [MSHADE-321] - Always respect 'createDependencyReducedPom' flag
>     * [MSHADE-371] - Update Shade Apache[Notice/LICENSE]ResourceTransformer to use also [NOTICE/LICENSE].md
>     * [MSHADE-373] - Source transformation on source jar can break OSGi resolution due to duplicated …

Update Maven Shade Plugin to 3.3.0

---

src/main/java/the/bytecode/club/bytecodeviewer/CommandLineInput.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/Decompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/ASMifierGenerator.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/DecompilerViewComponent.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/DecompilerSelectionPane.java
src/main/java/the/bytecode/club/bytecodeviewer/translation/TranslatedComponents.java
src/main/java/the/bytecode/club/bytecodeviewer/translation/TranslatedStrings.java
src/main/resources/translations/english.json

This adds ASMifier support to address #426. The code is pretty much the same as the ASM Textifier disassembler, just substituting `new Textifier()` with `new ASMifier()`.
This includes support for CLI, which I have tested successfully, and also fixed a typo that tells users to use `-decompiler-list` which is not valid. I noticed that some decompilers/disassemblers, such as ASM Textify, do not have CLI support, which I wouldn't mind adding (maybe in a separate PR).
Additionally, this PR adds an additional entry in `DecompilerComponentType`: `JAVA_NON_EDITABLE`. ASMifier output is logically not editable (similar to ASM Textifier) but outputs Java code and not Bytecode.
I have only added a translation under English, so I do not know if this would be a concern. …

Add ASMifier support

---

.github/workflows/maven.yml
pom.xml

This fixes the famous `MethodCodeTooLargeException`, compile issues, and updates dependencies.
Addendum: This also now updates the GitHub Actions since Node.js 12 actions are deprecated now.

Fix dex2jar issues

---

pom.xml

Updated dependencies due to IntelliJ complaining about various (transitive) dependency vulnerabilities; did not update ANTLR dependency. Initial testing with JADX and Fernflower decompilers as well as APKs works fine.
There are still three more complaints about (transitive) dependency vulnerabilities:
* `org.jboss.windup.decompiler:decompiler-fernflower` – Transitive dependency Apache Commons Collection: Cx78f40514-81ff (Uncontrolled recursion)
* `org.smali:smali` – Transitive dependency jcommander: Cx8fd408ac-dd80 (Inclusion of functionality from untrusted control sphere)
* `org.yaml:snakeyaml` – CVE-2022-41854 (6.5; stack-based buffer overflow)
These should probably be updated promptly when a new version is released.

Update dependencies as of this commit date

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/SearchableRSyntaxTextArea.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/CloseButtonComponent.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/DraggableTabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/TabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/Workspace.java

As commit says, I removed the portion of DND support I committed a few weeks/months ago, to enable the already supported DND from weisJ. I also, fixed an issue with having a class open and then switching theme and not being able to scroll. Don't know if it was just me or other people had this issue.
DND support - Windows theme doesn't work with this change, however the other themes do now. Possibly get rid of the basic windows theme all together?

DND Support and Scrolling

---

src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/contextmenu/resourcelist/Delete.java

For users who want bigger UI text, they are now able to do this. Caveat is having to press "Refresh" for updating the workspace.
https://github.com/Konloch/bytecode-viewer/assets/6558800/202f71f3-fba3-4808-9b21-ff5e7f535000

UI Font Size

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListPane.java

You would be unable to open files in the sidebar if you clicked on the empty space to the left / right of the file names in various situations
It's janky behaviour which has annoyed me for a while now

fix clicking on empty space in row not opening file

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/CloseButtonComponent.java

There is existing behaviour which lets you right click the "close tab" button, to show options to: "close all but this", "close tab"
But you could never use it because any mouse click (left or right) would simply close the tab.
Makes the app very tedious to use.
tl;dr you can now right click the "close tab" button to see and interact with its context menu

fix right-clicking close tab button closes popup menu

---

.github/workflows/maven.yml
pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/util/Dex2Jar.java
src/main/resources/translations/english.json
src/main/resources/translations/german.json

- Add AUTO_OPEN to I18n (I did that a while ago - cannot remember why)
- Use computeFrames in dex2jar (This yields more accurate output and circumvents a few bugs)
- Update actions to Node.JS 20 (the old Node.JS 16 versions have been deprecated quite some time ago already)
- Update dependencies in general (including webp-imageio to own fork supporting Java 8)
Hence, this PR:
Fixes #487

A few things

---

src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java

Font size spinner now updates the opened tabs without needing to click the "Refresh" button. I didn't realize there was already a method that would accomplish this. Also, since finding this method, I found that it would produce an exception, which is now fixed.

Font size spinner also updates opened tabs automatically now.

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/MyErrorStripe.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/RSyntaxTextAreaHighlighterEx.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/SearchableRSyntaxTextArea.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/TextAreaSearchPanel.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/actions/GoToAction.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/Workspace.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/viewer/ClassViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/util/BytecodeViewPanelUpdater.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/ClassFileContainer.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/locations/ClassFieldLocation.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/locations/ClassLocalVariableLocation.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/locations/ClassMethodLocation.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/locations/ClassParameterLocation.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/locations/ClassReferenceLocation.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/parser/MyVoidVisitor.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/parser/TokenUtil.java

Finally got this completed to a point where I believe it is ready for release.
Additions include:
- Field/Parameter/Local Variables parsing and highlighting
and,
- Go-To action for the Field/Parameter/Local Variable declaration
Possible add-ons:
- Parse/Go-To for classes without needing to select a field
- Parse/Go-To for method usages
Tested using FernFlower, JD-GUI and Procyon.

Token Parsing

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/util/BytecodeViewPanelUpdater.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/ClassFileContainer.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/parser/MyVoidVisitor.java

- Removed parsing for disassembly/bytecode
- Removed adding class reference when a "this." expression is parsed
- Removed parsing ConstructorDeclaration when in an anonymous body because it does not really need to be parsed

A few fixes for parsing

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/actions/GoToAction.java

As the title states, I removed the check for packages with similar package names as the JRE.
During the simple testing with it removed, everything works as usual, and no errors are thrown when trying to go to a class that is not included in the opened resource.
I also updated the RSyntaxTextArea version that removes all of the logging that was accidentally left in.

[Go-to] Removed the check for packages that start with "java", "javax", etc.

---

src/main/java/the/bytecode/club/bytecodeviewer/util/FileHeaderUtils.java

Hi,
This patch fixes an ArrayIndexOutOfBoundsException when the input array is smaller than the inspected range.

fix ArrayIndexOutOfBoundsException in FileHeaderUtils

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListIconRenderer.java

Hi,
The resource tree generation could be multiple seconds for large apks with the original implementation.
This patch significantly reduce the time spent on the generation.

speed up the resource file tree generation

---

src/main/java/the/bytecode/club/bytecodeviewer/compilers/impl/SmaliAssembler.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/SmaliDisassembler.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/ResourceContainerImporter.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/exporting/impl/DexExport.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/importing/impl/APKResourceImporter.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/importing/impl/DEXResourceImporter.java
src/main/java/the/bytecode/club/bytecodeviewer/util/SecurityMan.java
src/main/java/the/bytecode/club/bytecodeviewer/util/apk2Jar/Apk2Jar.java
src/main/java/the/bytecode/club/bytecodeviewer/util/apk2Jar/Dex2Jar.java
src/main/java/the/bytecode/club/bytecodeviewer/util/apk2Jar/Enjarify.java

Hi,
This patch removes the unnecessary compression/decompression of the jar files when using the Dex2Jar. The Dex2Jar can simply write the jvm classes to a folder.

skip compression & decompression when using Dex2Jar

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/util/BytecodeViewPanelUpdater.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/classcontainer/ClassFileContainer.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/MethodCallSearch.java

Hi,
This patch is fixes the now broken search (results can't be opened). It also ensures that the class files are opened under the same same, from both the file tree and from the search results.

bugfix to the broken search

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/hexviewer/HexViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/hexviewer/ValuesPanel.java

Update of binary viewer library

Binary viewer library update

---

src/main/java/the/bytecode/club/bytecodeviewer/plugin/PluginWriter.java

These usages break text direction, switching to right-to-left (RTL) instead of the expected left-to-right (LTR).
area.setCaretPosition(0); does the same and is already in place.
Tested on my side and this resolved the following issue
#549

Plugin Writer, Fix unexpected text direction behavior
