src/the/bytecode/club/bytecodeviewer/plugin/strategies/CompiledJavaPluginLaunchStrategy.java

Compiled Java Plugin Loading

---

src/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java

Fixed imports pointing to obsolete namespace

Fix project build

---

src/the/bytecode/club/bootloader/AbstractLoaderFactory.java
src/the/bytecode/club/bootloader/Boot.java
src/the/bytecode/club/bootloader/ClassPathLoader.java
src/the/bytecode/club/bootloader/EmptyExternalResource.java
src/the/bytecode/club/bootloader/ILoader.java
src/the/bytecode/club/bootloader/LibraryClassLoader.java
src/the/bytecode/club/bootloader/LoaderFactory.java
src/the/bytecode/club/bootloader/resource/DataContainer.java
src/the/bytecode/club/bootloader/resource/EmptyExternalResource.java
src/the/bytecode/club/bootloader/resource/ExternalLibrary.java
src/the/bytecode/club/bootloader/resource/ExternalResource.java
src/the/bytecode/club/bootloader/resource/JarContents.java
src/the/bytecode/club/bootloader/resource/JarInfo.java
src/the/bytecode/club/bootloader/resource/JarResource.java
src/the/bytecode/club/bootloader/resource/JarType.java
src/the/bytecode/club/bootloader/resource/LocateableJarContents.java
src/the/bytecode/club/bootloader/util/ClassHelper.java
src/the/bytecode/club/bootloader/util/ClassTree.java
src/the/bytecode/club/bootloader/util/NullCreator.java
src/the/bytecode/club/bootloader/util/NullPermeableHashMap.java
src/the/bytecode/club/bootloader/util/SetCreator.java
src/the/bytecode/club/bootloader/util/ValueCreator.java

kind of unacceptable.
fix.
-Bibl

kind of unacceptable.

---

src/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java

See #66.
I'm not totally sure about the formatting.

Prints invokeDynamic

---

.gitignore
src/the/bytecode/club/bytecodeviewer/gui/FileNavigationPane.java

It now selects the quick search pane.
Resolves #70.

Fix navigation pane typing behavior

---

src/the/bytecode/club/bytecodeviewer/gui/FileNavigationPane.java

Why was searching case insensitive to begin with?

Made searching case sensitive

---

src/the/bytecode/club/bytecodeviewer/JarUtils.java
src/the/bytecode/club/bytecodeviewer/api/BytecodeViewer.java
src/the/bytecode/club/bytecodeviewer/api/ClassNodeLoader.java
src/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java
src/the/bytecode/club/bytecodeviewer/gui/AllatoriStringDecrypterOptions.java
src/the/bytecode/club/bytecodeviewer/gui/FileNavigationPane.java
src/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java
src/the/bytecode/club/bytecodeviewer/plugin/preinstalled/AllatoriStringDecrypter.java
src/the/bytecode/club/bytecodeviewer/plugin/preinstalled/ZStringArrayDecrypter.java

BytecodeViewer is the best tool for working with bytecode I've found, but there was some bugs (probably fixed).
TODO: Add safe-reflection deobfuscation.

Added Allatori string deofuscator

---

src/the/bytecode/club/bytecodeviewer/JarUtils.java

It works like printf, why not use it like printf?

Clean up String.format

---

src/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/the/bytecode/club/bytecodeviewer/JarUtils.java

Clean up 0xCAFEBABE string (again)

---

pom.xml

Added some local dependencies referencing the jars in /libs now maven compiles the project 
Signed-off-by: northdpole <morfeas3000@gmail.com>

fixed the pom to compile the project

---

src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java

Reverts Konloch/bytecode-viewer#181

Revert "Update BytecodeViewer.java"

---

.gitignore
src/me/konloch/kontainer/io/DiskReader.java
src/the/bytecode/club/bytecodeviewer/decompilers/ProcyonDecompiler.java
src/the/bytecode/club/bytecodeviewer/util/EncodeUtils.java

add feature: Chinese characters support！

---

.gitignore
src/the/bytecode/club/bytecodeviewer/gui/FileNavigationPane.java
src/the/bytecode/club/bytecodeviewer/util/LazyNameUtil.java

fixbug：files are hidden when select and click "-" button
Closes #260

1. add feature: context menu (remove|expand|collapse) support  2.fixbug: Issue 260

---

libs/README.md

This one's self-explanatory :)

Document dependency release process

---

src/main/java/the/bytecode/club/bytecodeviewer/util/MiscUtils.java

Fixes a crash and adds new entries at the top now

Fix recent files

---

src/main/resources/translations/german.json
src/main/resources/translations/html/intro.english.html
src/main/resources/translations/html/intro.german.html
src/main/resources/translations/html/intro.mandarin.html

- Added Discord link to intros
- Updated German translations

Updated translations

---

src/main/java/the/bytecode/club/bootloader/Boot.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/CFRDecompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/JADXDecompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/ExternalResources.java
src/main/java/the/bytecode/club/bytecodeviewer/resources/importing/impl/DirectoryResourceImporter.java
src/main/java/the/bytecode/club/bytecodeviewer/util/MiscUtils.java

Fix some NPEs

---

.github/workflows/maven.yml

I think, it might make sense to test against all currently supported JDK versions

Test on all supported JDKs

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/jdgui/JDGUIClassFileUtil.java

This fixes new opcodes in java class files for the JD GUI decompiler

Fix JD GUI decompiler

---

pom.xml

Minor version updates and sorting some properties :)
Not much, but something that might be useful for someone at some time

Organize POM

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/ProcyonDecompiler.java

Fix closed stream for Procyon

---

pom.xml
src/main/java/me/konloch/kontainer/io/DiskReader.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/RunOptions.java
src/main/java/the/bytecode/club/bytecodeviewer/plugin/strategies/JavaPluginLaunchStrategy.java

- Update Procyon to stable 0.6
- Update Jadx
- General small code quality changes

Update some stuff

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/CFRDecompiler.java

The API code was mostly taken out of my project Threadtear. It now doesn't need to create temp files anymore and file names like "CON" or random crashes are not a problem anymore. Also the code output of CFR is now better, because it is tricked to think that every class is resolved. No more ugly void declarations.

Use the CFR API instead of old buggy method.

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/CFRDecompiler.java

This fixes a few issues I found in the other approach (I have also been working on this for a considerable amount of time :) ).
Fixes #396

Better approach to CFR decompilation

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/SearchableJTextArea.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/SearchableRSyntaxTextArea.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/SearchKeyAdapter.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcesearch/SearchType.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/MemberWithAnnotationSearch.java
src/main/java/the/bytecode/club/bytecodeviewer/translation/TranslatedComponents.java

Added a search for annotated members.
Improved quick search for class tree.

Various search fixes and additions

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java

Disassembler: Print line numbers

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/MethodNodeDecompiler.java

- Label indexes are ordered now.
- Fixed FrameNode representation.
- Now prints method return type at method declaration.
- Added space between VarInsnNode variable and opcode.
- Added try catch block comments at labels.

Various bytecode disassembler fixes / additions.

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/InstructionPrinter.java
src/main/java/the/bytecode/club/bytecodeviewer/decompilers/bytecode/MethodNodeDecompiler.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/SearchKeyAdapter.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcesearch/SearchBoxPane.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/LDCSearch.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/MemberWithAnnotationSearch.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/MethodCallSearch.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/RegexSearch.java

- Fixed some bugs i found.
- Small disassembler changes.
- Updated the UI to look better and be more usable.
- Class search now accepts "/" as package separator.

Bug fixes and UI fixes and other small stuff.

---

src/main/java/the/bytecode/club/bytecodeviewer/plugin/PluginWriter.java
src/main/java/the/bytecode/club/bytecodeviewer/plugin/strategies/CompiledJavaPluginLaunchStrategy.java

Fix plugin writer with compiled java plugins

---

pom.xml

Update ASM for Java 19 support

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceListPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourcelist/ResourceTreeNode.java

Hi,
I regularly check my apks with this app. With obfuscated ones which have lots of items in the root node, opening the apk / browsing in the file tree is very slow. This is a significant speed up.
Difference inside in the red rectagle with green:

Optimized resource tree building

---

src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/CloseButtonComponent.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/DraggableTabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/TabExitButton.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/TabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/Workspace.java

Added the ability to drag tabs.

Tab dragging

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/BytecodeViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/DraggableTabbedPane.java

This fixes a few warnings related to the POM and errors related to GUI-stuff.
**PLEASE DO NOT MERGE UNTIL THAT ONE LINE IS PROPERLY REVIEWED**

Fix warnings and errors

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/MainViewerGUI.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/components/SearchableRSyntaxTextArea.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/CloseButtonComponent.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/DraggableTabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/TabbedPane.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/Workspace.java
src/main/java/the/bytecode/club/bytecodeviewer/searching/impl/MemberWithAnnotationSearch.java
src/main/java/the/bytecode/club/bytecodeviewer/util/Dex2Jar.java

Some time has passed and it might be time again for this :)
This PR also contains #471 
Furthermore, dex2jar now prints out errors to the console if something bad happens

Update dependencies (again)

---

src/main/java/the/bytecode/club/bytecodeviewer/gui/resourceviewer/Workspace.java
src/main/java/the/bytecode/club/uikit/tabpopup/AbstractJTabbedPanePopupMenuHandler.java
src/main/java/the/bytecode/club/uikit/tabpopup/ITabPopupEventListener.java
src/main/java/the/bytecode/club/uikit/tabpopup/ITabZeroComponentEventListener.java
src/main/java/the/bytecode/club/uikit/tabpopup/JTabbedPanePopupEventHandler.java
src/main/java/the/bytecode/club/uikit/tabpopup/TabPopupEvent.java
src/main/java/the/bytecode/club/uikit/tabpopup/closer/JTabbedPaneCloser.java
src/main/java/the/bytecode/club/uikit/tabpopup/closer/JTabbedPanePopupMenuTabsCloser.java
src/main/java/the/bytecode/club/uikit/tabpopup/closer/PopupMenuTabsCloseConfiguration.java

Provide common UIKit, such as PopupMenu on the tabs.
Replace implementaion of close tabs in bytecodeviewer  Workspace.

Add Popup Menu for close Tabs

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/gui/hexviewer/HexViewer.java
src/main/java/the/bytecode/club/bytecodeviewer/gui/hexviewer/ValuesPanel.java

Update of BinEd library

---

src/main/java/the/bytecode/club/bytecodeviewer/decompilers/impl/FernFlowerDecompiler.java

Fix for #529.
Tested all other decompilers and no issues.

FernFlower destination fix

---

pom.xml
src/main/java/the/bytecode/club/bytecodeviewer/resources/importing/impl/APKResourceImporter.java
src/main/java/the/bytecode/club/bytecodeviewer/util/APKTool.java
src/main/java/the/bytecode/club/bytecodeviewer/util/JarUtils.java

Hi,
This patch reduces the time to load the resources from the apks. It removes the unnecessary jar compression/decompression and runs the apktool on multiple thread.

resources load optimization
